### ISSUE TITLE
Dieselgate: data in Popup wrong

### ISSUE THREAD

**Issue by joker234** [GIScience/openrouteservice-examples#18]
[Dieselgate example](https://github.com/GIScience/openrouteservice-examples/blob/master/python/Dieselgate_Routing.ipynb):
In the route popup the data seems to be wrong. The route with the profile driving-car doesn't take 46 minutes, and has only a distance of 0.4 km. A [similiar route using the ors webapp](http://maps.openrouteservice.org/directions?n1=52.501881&n2=13.399115&n3=14&a=52.520295,13.372582,52.508816,13.391519&b=0&c=0&k1=en-US&k2=km) takes 5 minutes and 2.8 km.

**Comment by koebi** [comment]
The current version of the dieselgate example doesn't have this issue anymore, both routes and popups look fairly reasonable.
