### ISSUE TITLE
Image not showing

### ISSUE THREAD

**Issue by HeidiSeibold** [GIScience/openrouteservice-examples#19]
In your examples the image at the top is not showing up.

E.g. https://openrouteservice.org/example-optimize-pub-crawl-with-ors/ it looks like this:

![image](https://user-images.githubusercontent.com/14146757/75239719-7d42f200-57c3-11ea-962e-c92cc3886d91.png)

**Comment by nilsnolde** [comment]
Thanks will amend!

**Comment by koebi** [comment]
I don't think this is an issue anymore, and will therefore close it. Feel free to re-open if the problem persists :)
