### ISSUE TITLE
TypeError in In[8] and ValueError in In[12]

### ISSUE THREAD

**Issue by fullmoonsky** [GIScience/openrouteservice-examples#22]
Hi, I am a newbie here, especially in the GIS related areas. While learning by practicing and digesting your provided Jupyter Examples (which were very helpful) – starting with example “**apartment search with openrouteservice**” (https://openrouteservice.org/example-apartment-search-with-ors/),  I ran into 2 errors and thought you might be interested in knowing (I’m not sure if it was because of my new environment (openrouteservice 2.3.3, python 3.8.8)):

**Error #1: TypeError in In[8]****

     17         params_poi['filter_category_ids'] = category
     18         apt['categories'][typ] = dict()
---> 19         apt['categories'][typ]['geojson']= clnt.places(**params_poi)['features'] # Actual POI request
     20         print("\t{}: {}".format(typ, # Print amount POIs
     21                                 len(apt['categories'][typ]['geojson'])))

TypeError: list indices must be integers or slices, not str

**Solution:**
The error was fixed after I changed line #19 to "_clnt.places(**params_poi)[0]['features'] # Actual POI_" (by adding a [0] before [features]. This was due to the fact that "_clnt.places(**params_poi)_" is a list, not a dict.

----------------------------------------------------------
**Error #2: ValueError in In[12]**

      1 # Sum up the closest POIs to each apartment
      2 for name, apt in apt_dict.items():
----> 3     apt['shortest_sum'] = sum([min(cat['durations']) for cat in apt['categories'].values()])
      4     print("{} apartments: {} mins".format(name,
      5                                           apt['shortest_sum']/60

<ipython-input-7-135d2e07fa9b> in <listcomp>(.0)
      1 # Sum up the closest POIs to each apartment
      2 for name, apt in apt_dict.items():
----> 3     apt['shortest_sum'] = sum([min(cat['durations']) for cat in apt['categories'].values()])
      4     print("{} apartments: {} mins".format(name,
      5                                           apt['shortest_sum']/60

ValueError: min() arg is an empty sequence

**Solution:** 
The error was fixed after I changed line #3 to "_sum([min(cat['durations'], default=0) for cat in apt['categories'].values()])_ " (by adding _default=0_ in the _min()_ method to avoid the error when there was an empty _cat[‘durations’]_.

**Comment by koebi** [comment]
Explanation as to why the second error happens can be found in [this post in the forum](https://ask.openrouteservice.org/t/apartment-search-exercise/2919/5)

**Comment by koebi** [comment]
Commit aa6072fda410e9e3b8f95de1876e229caa794f7e fixes the first issue and removes the second apartment after not finding any supermarkets, so this is no longer an issue.
