### ISSUE TITLE
Apartment _ Search

### ISSUE THREAD

**Issue by datamongerbonny** [GIScience/openrouteservice-examples#23]
I am unable to get the code in the second cell (POIs around apartments) to run (Apartment_Search.ipynb).!

<img width="320" alt="Screen Shot 2021-06-14 at 3 13 15 PM" src="https://user-images.githubusercontent.com/36204992/122043730-ad901480-cda9-11eb-8beb-843cccc9c647.png">

This is the error "list indices must be integers or slices, not str”

It should work as written. The first cell runs perfectly. I tried in Jupyter notebook and Colab in case it was a folium issue.

Thanks for any help. I want to adapt the code for another project in a different city...

Bonny

**Comment by koebi** [comment]
https://ask.openrouteservice.org/t/apartment-search-exercise/2919/2 related

**Comment by koebi** [comment]
Duplicate - closing in favor of #22
