### ISSUE TITLE
matrix API does not return symmetrical matrix

### ISSUE THREAD

**Issue by thegialeo** [GIScience/openrouteservice-examples#3]
Using the matrix API (metric=['distance']) does not yield a symmetrical matrix. However, the distance from node i to node j should be the same as from node j to node i (with i unequal j).

**Comment by nilsnolde** [comment]
It shouldn't be symmetrical really... There are one-way streets, opposite street sides etc prohibiting the results to be the exact same. However, they shouldn't be way off. If you have examples where it's not the same within a few %, please let us know.

**Comment by thegialeo** [comment]
Thanks, you are right. I didn't thought about one-way streets, ... etc. In this case, it does make sense that the matrix is not perfectly symmetrical.
