### ISSUE TITLE
jupyter notebook crash with ortools

### ISSUE THREAD

**Issue by thegialeo** [GIScience/openrouteservice-examples#4]
The jupyter notebook kernel crashes whenever the or-tool method pywrapcp.RoutingModel.SolveWithParameters() is executed. Copy paste the original google code (https://developers.google.com/optimization/routing/tsp/vehicle_routing) into a jupyter notebook and executing it, results in the same problem. Problem could not be solved yet.

**Comment by nilsnolde** [comment]
I'll have a look and get back to you.

**Comment by nilsnolde** [comment]
I made it work. Besides obviously converting to Py3 syntax, change 
`search_parameters = pywrapcp.DefaultRoutingSearchParameters()` to
`search_parameters = pywrapcp.RoutingModel.DefaultSearchParameters()`

**Comment by thegialeo** [comment]
Were you refering to my notebook or just to the link https://developers.google.com/optimization/routing/tsp/vehicle_routing. Because the change search_parameters = pywrapcp.DefaultRoutingSearchParameters() to
search_parameters = pywrapcp.RoutingModel.DefaultSearchParameters() was already been made in the notebook. Using  search_parameters = pywrapcp.DefaultRoutingSearchParameters() would yield method not found and when i google search  search_parameters = pywrapcp.RoutingModel.DefaultSearchParameters() was recommended as well. The problem lies in executing pywrapcp.RoutingModel.SolveWithParameters() were the kernel crashes. Could you execute the pywrapcp.RoutingModel.SolveWithParameters() method? Then maybe it is a local problem of my machine.
The problem is the code line: assignment = routing.SolveWithParameters(search_parameters)
