### ISSUE TITLE
Use geographic coordinates for VRP

### ISSUE THREAD

**Issue by nilsnolde** [GIScience/openrouteservice-examples#7]
No cartesian coordinates with shady conversion pls

**Comment by thegialeo** [comment]
I am not familiar with the geographic coordinates. From what I read on the wikipedia article, i assume geographic coordinates are just spherical coordinate. I can easily do a transformation from cartesian to spherical coordinates. Are there any specific conventions on geographical coordinates that i should know of (aka differences between spherical and geographical coordinates) or can i just set theta=latitude and phi=longitude?

**Comment by thegialeo** [comment]
latitude and longitude are now used
