### ISSUE TITLE
Make notebook more accessible

### ISSUE THREAD

**Issue by nilsnolde** [GIScience/openrouteservice-examples#8]
Generally:
- too scientific. Reads more like a thesis. Purpose: legibility and reproducibility.
- try to avoid methods. If much conciser, go ahead and define methods.
- I like the way you're printing dataframes. Consider printing df.head() though. Good to have reminders what the data looks like, but the whole table is not necessary.
- text blocks should be much shorter. Noone will read this if it's too long.

**Comment by thegialeo** [comment]
Ok, i will work on those points
