### ISSUE TITLE
Can't create isochrone in apartment_Search

### ISSUE THREAD

**Issue by ghost** [GIScience/openrouteservice-examples#9]
When running the  [/openrouteservice.org/example-apartment-search-with-ors](https://openrouteservice.org/example-apartment-search-with-ors/)-example, the creation of isochrone fails here 

```python
for name, apt in apt_dict.items():
    params_iso['locations'] = apt['location'] # Add apartment coords to request parameters
    apt['iso'] = clnt.isochrones(**params_iso) # Perform isochrone request
    folium.features.GeoJson(apt['iso']).add_to(map1) # Add GeoJson to map
```

With this error

```python
ApiError                                  Traceback (most recent call last)
<ipython-input-2-6fc3e64952b4> in <module>()
     19 for name, apt in apt_dict.items():
     20     params_iso['locations'] = apt['location'] # Add apartment coords to request parameters
---> 21     apt['iso'] = clnt.isochrones(**params_iso) # Perform isochrone request
     22     folium.features.GeoJson(apt['iso']).add_to(map1) # Add GeoJson to map
     23 

~/.local/lib/python3.6/site-packages/openrouteservice/client.py in wrapper(*args, **kwargs)
    290     def wrapper(*args, **kwargs):
    291         args[0]._extra_params = kwargs.pop("extra_params", None)
--> 292         result = func(*args, **kwargs)
    293         try:
    294             del args[0]._extra_params

~/.local/lib/python3.6/site-packages/openrouteservice/isochrones.py in isochrones(client, locations, profile, range_type, intervals, segments, units, location_type, attributes, intersections, dry_run)
    123         params["attributes"] = convert._pipe_list(attributes)
    124 
--> 125     return client.request("/isochrones", params, dry_run=dry_run)

~/.local/lib/python3.6/site-packages/openrouteservice/client.py in request(self, url, params, first_request_time, retry_counter, requests_kwargs, post_json, dry_run)
    206 
    207         try:
--> 208             result = self._get_body(response)
    209             self.sent_times.append(time.time())
    210             return result

~/.local/lib/python3.6/site-packages/openrouteservice/client.py in _get_body(self, response)
    232         if status_code != 200:
    233             raise openrouteservice.exceptions.ApiError(status_code,
--> 234                                                        body)
    235 
    236         return body

ApiError: 500 ({'error': {'code': 3099, 'message': 'Unable to build an isochrone map.'}, 'info': {'engine': {'version': '4.5.0', 'build_date': '2018-03-26T14:41:01Z'}, 'timestamp': 1525696593278}})
```

Is this working for you as it is?

**Comment by TimMcCauley** [comment]
@FredrikLindseth - sorry, trying to fix this, it's an error on our end, stay tuned

**Comment by TimMcCauley** [comment]
@FredrikLindseth this should be working again now - please let us know if it doesn't

**Comment by faisal100** [comment]
I have the same issue. but with a different error code.

for name, apt in apt_dict.items():
    params_iso['locations'] = apt['location'] # Add apartment coords to request parameters
    apt['iso'] = clnt.isochrones(**params_iso) # Perform isochrone request
    folium.features.GeoJson(apt['iso']).add_to(map1) # Add GeoJson to map



---------------------------------------------------------------------------
ApiError                                  Traceback (most recent call last)
<ipython-input-90-5a337ed5807a> in <module>
      1 for name, apt in apt_dict.items():
      2     params_iso['locations'] = apt['location'] # Add apartment coords to request parameters
----> 3     apt['iso'] = clnt.isochrones(**params_iso) # Perform isochrone request
      4     folium.features.GeoJson(apt['iso']).add_to(map1) # Add GeoJson to map

~\Anaconda3\lib\site-packages\openrouteservice\client.py in wrapper(*args, **kwargs)
    287     def wrapper(*args, **kwargs):
    288         args[0]._extra_params = kwargs.pop("extra_params", None)
--> 289         result = func(*args, **kwargs)
    290         try:
    291             del args[0]._extra_params

~\Anaconda3\lib\site-packages\openrouteservice\isochrones.py in isochrones(client, locations, profile, range_type, range, intervals, segments, interval, units, location_type, smoothing, attributes, validate, dry_run)
    133         params["attributes"] = attributes
    134 
--> 135     return client.request("/v2/isochrones/" + profile + '/geojson', {}, post_json=params, dry_run=dry_run)

~\Anaconda3\lib\site-packages\openrouteservice\client.py in request(self, url, get_params, first_request_time, retry_counter, requests_kwargs, post_json, dry_run)
    204 
    205         try:
--> 206             result = self._get_body(response)
    207 
    208             return result

~\Anaconda3\lib\site-packages\openrouteservice\client.py in _get_body(self, response)
    237             raise exceptions.ApiError(
    238                 status_code,
--> 239                 body
    240             )
    241 

ApiError: 400 ({'error': {'code': 3002, 'message': "Parameter 'locations' has incorrect value or format."}, 'info': {'engine': {'version': '5.0', 'build_date': '2019-03-13T16:21:40Z'}, 'timestamp': 1554635972686}})

**Comment by nilsnolde** [comment]
Hi,
yes, we need to look them over again as a lot has changed during the last year, new ORS version, new ors-py version etc.

I'll flag this in a new issue:
https://github.com/GIScience/openrouteservice-examples/issues/17
